name: Push Docker Image to GitHub Packages

on:
 push:
    branches:
      - main

jobs:
 build-and-push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up QEMU
      runs: if self.conclusion != 'success' || matrix.os == 'windows'; then echo "qemu"; fi
      shell: bash

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker image
      run: |
        docker build -t ghcr.io/$GITHUB_ACTOR/123456hdr/Docker-DB-GPT:latest .
        docker push ghcr.io/$GITHUB_ACTOR/123456hdr/Docker-DB-GPT:latest
